from importlib import import_module
from typing import Any

_EXPORT_MODULES: dict[str, str] = {
    "BATTLEFIELD_ARTIFACT_TYPE": "app.services.battlefield_service",
    "MAX_EVIDENCE_CARD_SUMMARY_CHARS": "app.services.battlefield_service",
    "BattlefieldService": "app.services.battlefield_service",
    "BattlefieldServiceError": "app.services.battlefield_service",
    "HUMAN_FEEDBACK_EFFECT_ARTIFACT_TYPE": "app.services.feedback_service",
    "FeedbackService": "app.services.feedback_service",
    "FeedbackServiceError": "app.services.feedback_service",
    "KNOWLEDGE_ARTIFACT_TYPE": "app.services.knowledge_retrieval",
    "KnowledgeRetrievalService": "app.services.knowledge_retrieval",
    "compact_knowledge_for_llm": "app.services.knowledge_retrieval",
    "LLMCallResult": "app.services.llm_client",
    "LLMClient": "app.services.llm_client",
    "LLMSettings": "app.services.llm_client",
    "LLMTokenUsage": "app.services.llm_client",
    "load_llm_settings": "app.services.llm_client",
    "DEFAULT_REPORTS_DIR": "app.services.markdown_renderer",
    "NO_RELIABLE_DATA": "app.services.markdown_renderer",
    "MarkdownRenderError": "app.services.markdown_renderer",
    "export_markdown_report_for_state": "app.services.markdown_renderer",
    "render_markdown_report": "app.services.markdown_renderer",
    "OVERVIEW_ARTIFACT_TYPE": "app.services.overview_service",
    "OverviewService": "app.services.overview_service",
    "OverviewServiceError": "app.services.overview_service",
    "MAX_EVIDENCE_SUMMARY_CHARS": "app.services.profile_service",
    "PRODUCT_PROFILE_ARTIFACT_TYPE": "app.services.profile_service",
    "ProfileService": "app.services.profile_service",
    "ProfileServiceError": "app.services.profile_service",
    "build_public_page_evidence": "app.services.public_page_enrichment",
    "enrichment_result_payload": "app.services.public_page_enrichment",
    "PublicPageFetcher": "app.services.public_page_fetcher",
    "PublicPageFetchError": "app.services.public_page_fetcher",
    "fetch_snapshot_payload": "app.services.public_page_fetcher",
    "public_page_fetch_error_payload": "app.services.public_page_fetcher",
    "ParsedPublicPage": "app.services.public_page_parser",
    "PublicPageParseError": "app.services.public_page_parser",
    "parse_public_page_snapshot": "app.services.public_page_parser",
    "parsed_public_page_payload": "app.services.public_page_parser",
    "DEFAULT_ALLOWED_DOMAINS": "app.services.public_page_policy",
    "DEFAULT_MAX_PUBLIC_PAGES_PER_TASK": "app.services.public_page_policy",
    "PublicPagePolicyDecision": "app.services.public_page_policy",
    "PublicPageUrlCandidate": "app.services.public_page_policy",
    "evaluate_public_page_candidates": "app.services.public_page_policy",
    "policy_decisions_summary": "app.services.public_page_policy",
    "public_page_policy_decision_payload": "app.services.public_page_policy",
    "run_qa_rules": "app.services.qa_rules",
    "RELATIONSHIP_GRAPH_ARTIFACT_TYPE": "app.services.relationship_graph_service",
    "RelationshipGraphService": "app.services.relationship_graph_service",
    "RelationshipGraphServiceError": "app.services.relationship_graph_service",
    "render_relationship_graph_png": "app.services.relationship_graph_service",
    "MARKDOWN_REPORT_ARTIFACT_TYPE": "app.services.report_service",
    "REPORT_ARTIFACT_TYPE": "app.services.report_service",
    "ReportService": "app.services.report_service",
    "ReportServiceError": "app.services.report_service",
    "SCORE_WEIGHTS": "app.services.scoring",
    "CompetitionScoreResult": "app.services.scoring",
    "DimensionScore": "app.services.scoring",
    "ScoredCompetitor": "app.services.scoring",
    "calculate_competition_edge_score": "app.services.scoring",
    "rank_competitors_by_score": "app.services.scoring",
    "DEFAULT_SNAPSHOT_PATH": "app.services.snapshot_loader",
    "SnapshotLoaderError": "app.services.snapshot_loader",
    "SnapshotLoadResult": "app.services.snapshot_loader",
    "load_demo_snapshot": "app.services.snapshot_loader",
    "StructuredModelOutputResult": "app.services.structured_output",
    "coerce_structured_model_output": "app.services.structured_output",
    "TaskCreationError": "app.services.task_creation",
    "TaskCreationService": "app.services.task_creation",
    "COMPETITOR_BATTLECARD_ARTIFACT_TYPE": "app.services.task_execution",
    "GAP_MATRIX_ITEM_ARTIFACT_TYPE": "app.services.task_execution",
    "OPPORTUNITY_ITEM_ARTIFACT_TYPE": "app.services.task_execution",
    "REPORT_QUALITY_CHECK_ARTIFACT_TYPE": "app.services.task_execution",
    "STRATEGY_BRIEF_ARTIFACT_TYPE": "app.services.task_execution",
    "TaskExecutionError": "app.services.task_execution",
    "TaskExecutionService": "app.services.task_execution",
    "TRACE_ARTIFACT_TYPE": "app.services.trace_service",
    "TraceService": "app.services.trace_service",
    "TraceServiceError": "app.services.trace_service",
    "NO_RELIABLE_IMAGE": "app.services.word_report_service",
    "WORD_REPORT_ARTIFACT_TYPE": "app.services.word_report_service",
    "WordRenderError": "app.services.word_report_service",
    "WordReportService": "app.services.word_report_service",
    "WordReportServiceError": "app.services.word_report_service",
    "render_word_report": "app.services.word_report_service",
}


__all__ = sorted(_EXPORT_MODULES)


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module 'app.services' has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value
